version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: defi-meninges-db
    environment:
      POSTGRES_DB: defimeninges
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: