# Application name
spring.application.name=defi-meninges-api

# Global CORS Configuration for Angular frontend
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}

# Database Configuration (PostgreSQL via Environment Variables)
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in the console for debugging
spring.jpa.show-sql=true