# Application name
spring.application.name=defi-meninges-api

# Environment Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# URLs
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}
app.api.base-url=${BACKEND_URL:http://localhost:8080}

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in the console for debugging
spring.jpa.show-sql=true

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS:1800000}
app.jwt.refresh-token-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000}